dist: xenial
sudo: false
language: python
python:
  - "3.9"

env:
  global:
    - secure: g/ta2yudfA55ruxd+GHxYQUd39OM/hoEhNp0KgPm3QINaXwaB6C9eQ31qOi/i9OiSjmVwISE+yUaPtQP2jtbYnkS/SHiRNvzhfA+mPrT0n0hoVSNIlxl94E8hoPBZr2jlYVQ6dIuT98mIRYJu/wiGHDQCuar6znpiKFB1/gyUszvZxAxHJIe5EcjuXWFnre91b96tNkZRKJZv+Jst0CkknVcKAZ4kmC/o5Z1hr5VaMekRV5SKf+vMEfVc+W9VktqDBgKwaFIwWqSgQFk5LOnPr/EZq8mrqPpa+LFaLiQpDGDAdaVEM0/A3dzx3YnYoBFNr5hmCtoCLWccxC+diaw3kZuTX6olxn8cbRCVf8lu4JuJKFU5CgTLS7NBH3Rpk4iRE7C9v4W+QKjw3CJxLCMoMqQCbYx6GjzjZYbZBA6jvaS6ZFe41N6egA0SpNvKtfYU9TR7lNVwGehRIY9kycOEX5ZQInkqILxz5YHrkMNfICdLY+rYFBDvgNAOZxYR1tLaOG9jYuUbBOLVRZz78wkPrXynquay6HZn7AxBxOdnvGQAkINvo40Lx/MWdZ88o3f/th838cpPCxBRQZ5Kn3RkHNhGHwUJadsbaOLnKrj3ISaTOvq0brA1mxJFyJwoVrn+rFs80CWRonQ5lQeaOHf0p1flH7j+TFhl/INkvXsf7Y=  # PGPASSWORD
    - secure: UVP6sQTPglNAWxok8MmKfd9vWrY9uOCnJqWb8Qcw052+Au2BRDafN3yZJ3ekyQaHiAblbz/NitosxETT/Rjf6Bzlw2zWqscJOKPVEBZgdA3tTLUTN8pzb8bVKGUl8CBLMIj+q0rx1dDYukIF+9WYrySp5ubqAhG3hR9z0BlnJdSD2b8tNR/r5ncXRvtxwR6KRjQfE2sERvXEq4x0wxZA/OjnpPnf4mQ3k26Z2k/qE7+DtBKLk2HcnN1BQMa0+VPrCbLYG+ZogZendYWFgr+j8JLM0J6vOGXWTCIiCLhjBUJZSENJHDLDy+NoMAY9raHOC/64xxNykvBx2Pljwdla1UwLBVSj8r5dK5irzrE41fJYsRc/d7HtVwFBUQp1HquyccRwLJ2jAMcGEoc0OJnUeFowbqrb0WFu9dyibd/sq2JPfHvlY5UxBCaiWGi3pnSBN+jQYbByKMxPMg/+RojVIvRDTqtSqN/WNj98OlGfTNDT9McbCSErLdYNyWyzj58R58FkLZVBsTYujHd+6vJRhzdqgDCDie6ORpd3lh+Rs7s6vEKXGXVOvrQ2CoCm6gAzHpcCaL0LqhpqU8ps2eZ7fXN5pOe5XHLnvhacYAAIBwEPp0Y7ONlBgoYbnObEUn2micGKt2PPgq7flM65u1Pi2NRpsIyI1PBGWMzq2fWttPI=  # VPC_SECURITY_GROUP_ID
    - secure: IUyT6kZQncTAXL1A5OYvT9pLQ6jpd4YXhzQC4NonZ+w/ZfJRGeZf/o2OSZYjWlLl3jVLpbPC3bQs3duAwERQOPrQ15M1jRYE9ChG8ZCkVCcWYDr16HmpQZyV+M0jXy6v1eKtjsZg0pmitKTgWHCFwzjyyBMkfcBveLApbRXTGueTFnclKtSOrupAOggoK4eJHIKS7c0mDU8/TS5ae6l66Yt37+KEN0ihN3OBIsD9f+QRwHRdGEHSGXh8Cp25l3uoxS+LDxpMa4h9K6S4Id2NXtFFLed7JN9qpgWauTcJQjSsXC8QX2UfmLZ1GBpz9nmUVOtQDOe2TqlcAQs/CPiwB8an0Ez1D9pUJp3MGyGA0lq1bg+fexYqzkWdwS5R8w4R0dwkFbCkoMKR8hcDDIrDXf+4Nf/Ry49ZBB/8ejuW/huyZMkRAaGgoHvjoCeGwNyu5PwYk9BHY7wjLKuRUtKNq8y1+0HYbw3oiE+1WPT60kmoKo9Rv1yeUZ/Faq9FEFf+b62egmKkx/2EYPbnb17zHaXsAwezeaH8NnG/C0n66rtdsEnIvK/z9UZm0R+OlNMzWWQu3y1VyGmtnKcRfZAWfC7XxeTMpM9dd9N1R1vtxv/sxduoqsBeaQlgzIa+NhQ6wUAxf5114EmDsIM7S9TsHL0jP51emLw1cSXCNvSGM2k=  # IAM_ROLE_ARN
matrix:
  include:
    - python: "3.9"
      env: TOXENV=lint
    - python: "3.9"
      env: TOXENV=docs

install: pip install tox tox-travis
script: tox
cache: pip
